title: SAFE
description: Security awareness for everyone

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

color_scheme: dark

collections:
  blogs:
    output: true
    permalink: /blogs/:path/
